apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: nextjs-typegraphql-app
  title: Next.js and TypeGraphQL App
  description: A Next.js app with an TypeGraphQL server.
spec:
  owner: user:guest
  type: service

  parameters:
  - title: Fill in some metadata
    required:
    - name
    properties:
      name:
        title: Name
        type: string
        description: Unique name of the component
        ui:autofocus: true
        ui:options:
          rows: 5
      owner:
        title: Owner
        type: string
        description: Owner of the component
        ui:field: OwnerPicker
        ui:options:
          catalogFilter:
            kind: Group
      description:
        title: Repository Description
        type: string
        description: Description of repository
      repoVisibility:
        title: Repository Visibility
        type: string
        description: Visibility of repository
        default: public
        enum:
        - public
        - private
        - internal
        enumNames:
        - Public
        - Private
        - Internal
  - title: Choose a location
    required:
    - repoUrl
    properties:
      repoUrl:
        title: Repository Location
        type: string
        ui:field: RepoUrlPicker
        ui:options:
          allowedHosts:
          - github.com

  steps:
  - id: fetch-base
    name: Fetch Base
    action: fetch:template
    input:
      url: https://github.com/vernaldev/template-nextjs-typegraphql
      values:
        name: ${{ parameters.name }}
        owner: ${{ parameters.owner }}

  - id: publish
    name: Publish
    action: publish:github
    input:
      allowedHosts: ['github.com']
      description: ${{ parameters.description }}
      repoUrl: ${{ parameters.repoUrl }}
      repoVisibility: ${{ parameters.repoVisibility }}

  - id: register
    name: Register
    action: catalog:register
    input:
      repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
      catalogInfoPath: '/catalog-info.yaml'

  output:
    links:
    - title: Repository
      url: ${{ steps['publish'].output.remoteUrl }}
    - title: Open in catalog
      icon: catalog
      entityRef: ${{ steps['register'].output.entityRef }}
